### ISSUE TITLE
Semver broken

### ISSUE THREAD

**Issue by rolandschuetz** [KaufmannDigital/CleverReach#17]
The bugfix release 2.1.1 did include a breaking change [Task: Use CleverReach API V3](https://github.com/KaufmannDigital/CleverReach/commit/b11bc65f5b00790218d6411f258fee622bcd0d8c) making the old way of passing a login to the package invalid.

**Comment by Nikdro** [comment]
Hi @rolandschuetz! 

Thanks for your hint. We noticed, that the Version was tagged on the wrong branch, which leads to this behavior.   
The Version 2.1.1 is now removed and replaced with a new Version 2.1.2 (to prevent composer getting problems with upgrading/requireing)

Would be great, if you check your setup with version 2.1.2.

**Comment by rolandschuetz** [comment]
Great, works :)
